config/routes.rb
Rails.application.routes.draw do
    root to: 'dots#index'
    get '/spotify_analyze', to: 'dots#spotify_analyze'
    get '/search', to: 'dots#search'
    post '/upload', to: 'dots#upload'
end

app/models/s3.rb
class S3
  BUCKET_NAME = ENV["S3_BUCKET_NAME_TD"]

  attr_reader :file, :track_name

  def initialize(options = {})
    @file       = options[:songfile]
    @track_name = sanitize(options[:track_name])
  end

  def tracks_list
    s3.list_objects(bucket: BUCKET_NAME).first.contents
  end

  def upload_track
    response        = create_multipart_upload
    upload_response = upload_part(response.upload_id)
    complete_multipart_upload(response.upload_id, upload_response.etag)
  end

  def audio_file
    "https://s3.amazonaws.com/#{BUCKET_NAME}/#{track_name}"
  end

  private

  def create_multipart_upload
    s3.create_multipart_upload({
      acl: "public-read",
      bucket: BUCKET_NAME,
      key: track_name,
    })
  end

  def upload_part(upload_id)
    s3.upload_part({
      body: file.tempfile,
      bucket: BUCKET_NAME,
      content_length: 1,
      key: track_name,
      part_number: 1,
      upload_id: upload_id
    })
  end

  def complete_multipart_upload(upload_id, etag)
    s3.complete_multipart_upload({
      bucket: BUCKET_NAME,
      key: track_name,
      multipart_upload: {
        parts: [
          {
            etag: etag,
            part_number: 1,
          }
        ]
      },
      upload_id: upload_id
    })
  end

  def sanitize(name)
    return unless name
    name.strip.downcase.gsub(/[^\w\.\-]/, "_")
  end

  def s3
    @s3 ||= begin
      Aws::S3::Client.new(
        :access_key_id => ENV["AWS_ACCESS_KEY_ID"],
        :secret_access_key => ENV["AWS_SECRET_KEY_ID"]
      )
    end
  end
end

app/models/spotify_authorization.rb
class SpotifyAuthorization
  URL = "https://accounts.spotify.com/api/token"
  BODY = { "grant_type" => "client_credentials" }

  def run
    response = HTTParty.post(URL, body: BODY, headers: header)
    response.dig("access_token")
  end

  def header
    { "Authorization" => "Basic #{encoded_keys}" }
   end

  def encoded_keys
    Base64.strict_encode64(
      "#{ENV['SPOTIFY_CLIENT_ID']}:#{ENV['SPOTIFY_CLIENT_SECRET']}"
    )
  end
end

app/models/track_analyzer.rb
class TrackAnalyzer
  SEARCH_BASE_URL         = "https://api.spotify.com/v1/search?q="
  TRACK_BASE_URL          = "https://api.spotify.com/v1/tracks/"
  AUDIO_ANALYSIS_BASE_URL = "https://api.spotify.com/v1/audio-analysis/"

  attr_reader :track_name, :access_token

  def initialize(track_name, access_token)
    @track_name = track_name
    @access_token = access_token
  end

  def run
    track_id    = spotify_track_id
    track       = spotify_track(track_id)
    analysis    = audio_analysis(track_id)
    artist_name = track["artists"].first["name"]
    track_name  = track["name"]

    { artist: artist_name, track: track_name, analysis: analysis.to_h }
  end

  def spotify_track_id
    request_url = SEARCH_BASE_URL + encode_track_name + "&type=track"
    response    = HTTParty.get(request_url, headers: auth_header)
    tracks      = response["tracks"]["items"]

    begin
      find_by_track_name(tracks)
    rescue NoMethodError
      tracks.first["id"]
    end
  end

  private

  def spotify_track(track_id)
    request_url = TRACK_BASE_URL + track_id
    HTTParty.get(request_url, headers: auth_header)
  end

  def audio_analysis(id)
    request_url = AUDIO_ANALYSIS_BASE_URL + id
    HTTParty.get(request_url, headers: auth_header)
  end

  def find_by_track_name(tracks)
    tracks.select { |item| decode(track_name) == item["name"].downcase }.first["id"]
  end

  def auth_header
    { "Authorization" => "Bearer #{access_token}" }
  end

  def encode_track_name
    track_name.gsub("_","+")
  end

  def decode(track_name)
    track_name.gsub("_"," ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dots_controller.rb
class DotsController < ApplicationController

  def index
    @temp_songs = S3.new.tracks_list
  end

  def spotify_analyze
    params.permit(:track_name)
    track_name  = params[:track_name].presence || "by the way"
    response    = TrackAnalyzer.new(track_name, access_token).run
    audio_file  = S3.new(track_name: track_name).audio_file

    render json: {
      artist: response[:artist],
      song: response[:track],
      meta_data: response[:analysis],
      file: audio_file
    }
  end

  def upload
    params.permit(:track_name, :songfile)

    S3.new(
      track_name: params[:track_name],
      songfile: params[:songfile]
    ).upload_track

    redirect_to root_path
  end

  private

  def access_token
    SpotifyAuthorization.new.run
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dots/index.html.erb
<div id="upload-form-container">
  <%= form_tag upload_path, :method => "post", :multipart => true, :id => 'upload-form' do %>
    <%= label_tag 'Upload a new song for analysis' %>
    <br>
    <span id="label-sub-text">(This could take up to a minute)</span>
    <br><br>
    <%= label_tag "What's the name of the song?" %>
    <br><br>
    <%=  text_field_tag "track_name", "", placeholder: "Song Name", required: true %>
    <br><br>
    <%= file_field_tag "songfile", required: true %>
    <%= image_tag('loadingGif.gif', id: 'loading-gif') %>
    <br><br>
    <%= submit_tag "Upload" %>
  <% end %>
</div>
<h1>Trippin' Dots</h1>
<em>Don't worry about scrolling, we'll do that for you.</em>
<br><br>
<a id="confused-link" href="#">I'm confused</a>
<div id="confused-text">
  <p>
    Click "Start Trippin'" next to a song to see it's visualization.
    Each section is broken down into its appropriate sections, and a dot is placed on the screen for each important note played.
    Some songs sync better than others. You can use the sensitivity slider to adjust the frequency of dots. Lower Sensitivity = More Dots
  </p>
</div>
<div id='search-form'>
  <h2>Temporary Songs (songs expire daily)</h2>
  <% @temp_songs.each do |song| %>
    <div class="song-item">
      <p id=<%= song.key %>><%= song.key %></p><button class="analyze-button">Start Trippin'</button>
    </div>
  <% end %>
  <label for="sensitivity-input">Sensitivity</label>
  <input id="sensitivity-input" name="sensitivity-slider" type="range" min="0" max="100" value="50" onchange="printValue('sensitivity-input', 'sensitivity-value')">
  <input id="sensitivity-value" type="number" name="sensitivity-number" min="0" max="100" value="50" size="5">
</div>

<script>
  function printValue(sliderID, textbox) {
      var x = document.getElementById(textbox);
      var y = document.getElementById(sliderID);
      x.value = y.value;
  }

  window.onload = function() { printValue('sensitivity-input', 'sensitivity-value') }
</script>

<div id="trippin-display"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trippindots</title>
<!--   We're visualizing songs with dots using the Echo Nest and iTunes APIs. The concept was to create dots the represent the intensity of a note or sound and break the representation into to segments based on the Echonest analysis. The user can search for a song and it will pull the data load it and represent it dynamically.

Team Members: Alex Shook, Ash Kamel, Jesse Sessler, Verner D'souza

See the code at https://github.com/alexshook/trippindots

Tripping dots was created during an 8 hour hackathon at the Etsy Month Music Hackathon -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>